library(shiny)
library(dplyr)
library(tidyr)
library(ggplot2)
library(ggsankey)
library(forcats)
library(treemapify)
library(rfm)
library(maps)
library(gridExtra)
library(RPostgres)
library(DBI)
library(lubridate)
library(DT)
library(openxlsx)
library(glue)
library(plotly)


readRenviron("./.Renviron")