version: '3.8'

services:
 app_segmentation:
  build:
   context: .
   dockerfile: Dockerfile
  ports:
   - 3838:3838
  #volumes:
  # - .:/app
  environment:
      - ADD=shiny
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
  restart: always